#simple make for ComMBE
CoOMBE : general_settings_2st.f90 ldbl.f90 obe.f90 mbe.f90 driveall.f90
	gfortran -o CoOMBE general_settings_2st.f90 ldbl.f90 obe.f90 mbe.f90 driveall.f90 -llapack -lblas
#clean:
#	rm -f CoOMBE.o CoOMBE.exe
#end of makefile 
