#simple make for ComMBE
ComMBE : general_settings_24st.f90 ldbl.f90 obe.f90 mbe.f90 driveall.f90
	gfortran -o ComMBE general_settings_24st.f90 ldbl.f90 obe.f90 mbe.f90 driveall.f90 -llapack -lblas
#clean:
#	rm -f ComMBE.o ComMBE.exe
#end of makefile 
