#simple make for honors
honours : general_settings_4st.f90 ldbl.f90 obe.f90 mbe.f90 driveall.f90
	gfortran -o honours general_settings_4st.f90 ldbl.f90 obe.f90 mbe.f90 driveall.f90 -llapack -lblas
#clean:
#	rm -f honors.o honors.exe
#end of makefile 
